# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-16 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility', models.CharField(max_length=50)),
                ('mechanics', models.CharField(max_length=50)),
                ('force', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('target_muscle', models.CharField(max_length=50)),
                ('apparatus', models.CharField(max_length=50)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exrx.Classification')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.TextField()),
                ('execution', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exrx.Instruction'),
        ),
    ]
